Feature/packer implementation (#12)
* Added Packer files and script

* Create packer-validation.yml

* Added file path for validate

* Changed the file path of script

* Added code to show the errors

* Changed the dir for validate

* Removed unwanted code

* Added script file for validate

* Added packer init

* Added file path of packer

* Added packer init

* Added packer init in workflow

* Added latest runner

* Added version for packer runner

* Removed clear

* Changed the runner to PR

* Removed unwanted file

* Changes made to script file

diff --git a/.github/workflows/packer-validation.yml b/.github/workflows/packer-validation.yml
--- a/.github/workflows/packer-validation.yml
+++ b/.github/workflows/packer-validation.yml
@@ -49,5 +49,12 @@ jobs:
         run: echo "Packer Validation starts"
 
       - name: Validate Packer Configuration
-        run: ./validate-packer.sh
+        run: |
+          echo "Validating Packer configuration..."
+          if packer validate packer/aws-ami.pkr.hcl; then
+            echo "Packer configuration is valid."
+          else
+            echo "Packer configuration validation failed."
+            exit 1
+          fi
 
