changed ami id retrival

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -80,7 +80,15 @@ jobs:
 
     - name: Packer Build
       run: |
-        packer build -var-file=packer/packer-config.hcl packer/aws-ami.pkr.hcl
+        ami_id=$(packer build -var-file=packer/packer-config.hcl packer/aws-ami.pkr.hcl | awk '/AMIs were created:/ {print $NF}')
+
+        if [ -z "$ami_id" ]; then
+          echo "Error: No valid AMI ID found. Exiting."
+          exit 1
+        fi
+
+        echo "Found AMI_ID: $ami_id"
+        echo "AMI_ID=$ami_id" > ami_id.txt
       
     - name: Set up AWS CLI for dev
       uses: aws-actions/configure-aws-credentials@v1
@@ -88,16 +96,6 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
         aws-region: ${{ secrets.AMI_AWS_REGION }}
-
-    - name: Get AMI ID and store it in a text file
-      run: |
-        ami_id=$(aws ec2 describe-images \
-        --filters "Name=tag:Name,Values=csye6225_2023_*" \
-        --query 'Images | sort_by(@, &CreationDate) | [-1].[ImageId]' \
-        --output text)
-
-        echo "Found AMI_ID: $ami_id"
-        echo "AMI_ID=$ami_id" > ami_id.txt
 
     - name: Update Launch Template with new AMI ID
       run: |
@@ -108,7 +106,7 @@ jobs:
           exit 1
         fi
 
-        ami_id=$(cat ami_id.txt)
+        ami_id=$(cat ami_id.txt | awk -F= '/AMI_ID/ {print $2}' | tr -d ' ')
 
         echo "Launch Template ID: $launch_template_id"
 
