changed ami id and launch template

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -1,6 +1,6 @@
 name: Build AMI and Include Artifact
 
-on: [ push ]
+on: [push]
 
 env:
   HOST: "localhost"
@@ -12,117 +12,119 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Starting Node JS message
-      run: echo "Setting up Node JS"
+      - name: Starting Node JS message
+        run: echo "Setting up Node JS"
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: 14
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 14
 
-    - name: Finishing Node JS set up message
-      run: echo "Node JS installation done"
+      - name: Finishing Node JS set up message
+        run: echo "Node JS installation done"
 
-    - name: Starting installation for mysql-server
-      run: echo "mysql-server installation done"
-        
-    - name: configuremysql
-      run: |
-        sudo apt-get update
-        sudo systemctl start mysql
-        sudo systemctl status mysql
-        mysql -u root -p"${PASSWORD}" -e "CREATE DATABASE Assignments_Demo_DB;"
+      - name: Starting installation for mysql-server
+        run: echo "mysql-server installation done"
 
-    - name: Starting dependency installation
-      run: echo "Installing Dependencies"
+      - name: configuremysql
+        run: |
+          sudo apt-get update
+          sudo systemctl start mysql
+          sudo systemctl status mysql
+          mysql -u root -p"${PASSWORD}" -e "CREATE DATABASE Assignments_Demo_DB;"
 
-    - name: Install dependencies
-      run: npm install
+      - name: Starting dependency installation
+        run: echo "Installing Dependencies"
 
-    - name: Dependency installation completed
-      run: echo "Dependencies Installed"
+      - name: Install dependencies
+        run: npm install
 
-    - name: Running test files
-      run: echo "Starting test"
+      - name: Dependency installation completed
+        run: echo "Dependencies Installed"
 
-    - name: run tests
-      run: npm test
+      - name: Running test files
+        run: echo "Starting test"
 
-    - name: Zip the artifact
-      run: |
-        zip -r webapp.zip ./
-        ls -lrth
+      - name: run tests
+        run: npm test
 
-    - name: Upload artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: app-artifact
-        path: webapp.zip
+      - name: Zip the artifact
+        run: |
+          zip -r webapp.zip ./
+          ls -lrth
 
-    - name: Set up AWS CLI
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AMI_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AMI_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AMI_AWS_REGION }}
+      - name: Upload artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: app-artifact
+          path: webapp.zip
 
-    - name: Setup `packer`
-      uses: hashicorp/setup-packer@main
-      id: setup
-      with:
-        version: 'latest'
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AMI_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AMI_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AMI_AWS_REGION }}
 
-    - name: Packer Init
-      run: packer init packer/aws-ami.pkr.hcl
+      - name: Setup `packer`
+        uses: hashicorp/setup-packer@main
+        id: setup
+        with:
+          version: "latest"
 
-    - name: Packer Build
-      id: get_ami_id
-      run: |
-        packer build -var-file=packer/packer-config.hcl packer/aws-ami.pkr.hcl
+      - name: Packer Init
+        run: packer init packer/aws-ami.pkr.hcl
 
-    - name: Set up AWS CLI for dev
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
-        aws-region: ${{ secrets.AMI_AWS_REGION }}
+      - name: Packer Build
+        id: get_ami_id
+        run: |
+          packer build -var-file=packer/packer-config.hcl packer/aws-ami.pkr.hcl
 
-    - name: Update Launch Template with new AMI ID
-      run: |
-        launch_template_id=$(aws ec2 describe-launch-templates --launch-template-name csye6225-dev-launch-template --region ${{ secrets.AMI_AWS_REGION }} --query 'LaunchTemplates[0].LaunchTemplateId' --output json)
+      - name: Set up AWS CLI for dev
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
+          aws-region: ${{ secrets.AMI_AWS_REGION }}
 
-        if [ -z "$launch_template_id" ]; then
-          echo "Error: Launch template ID not found or empty. Exiting."
-          exit 1
-        fi
+      - name: Update Launch Template with new AMI ID
+        run: |
+          launch_template_id=$(aws ec2 describe-launch-templates --launch-template-name csye6225-dev-launch-template --region ${{ secrets.AMI_AWS_REGION }} --query 'LaunchTemplates[0].LaunchTemplateId' --output json)
 
-        echo "Launch Template ID: $launch_template_id"
+          if [ -z "$launch_template_id" ]; then
+            echo "Error: Launch template ID not found or empty. Exiting."
+            exit 1
+          fi
 
-        launch_template_id=$(echo "$launch_template_id" | tr -d '"')
+          echo "Launch Template ID: $launch_template_id"
 
-        echo "Launch Template ID without quotes: $launch_template_id"
+          launch_template_id=$(echo "$launch_template_id" | tr -d '"')
 
-        aws ec2 create-launch-template-version \
-          --launch-template-id $launch_template_id \
-          --source-version 1 \
-          --launch-template-data '{"ImageId":"'"${{ steps.get_ami_id.outputs.ami_id }}"'"}'
+          echo "Launch Template ID without quotes: $launch_template_id"
 
+          ami_id="${{ steps.get_ami_id.outputs.ami_id }}"
 
-    - name: Update Auto Scaling Group with new Launch Template
-      run: |
-        asg_name=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
+          echo "AMI ID from step: ${{ steps.get_ami_id.outputs.ami_id }}"
 
-        launch_template_id=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?AutoScalingGroupName=='$asg_name'].LaunchTemplate.LaunchTemplateId" --output text)
+          echo "AMI ID after assigning: $ami_id"
 
-        aws autoscaling update-auto-scaling-group --auto-scaling-group-name $asg_name --launch-template LaunchTemplateId=$launch_template_id,Version=$launch_template_version
+          if [ -z "$ami_id" ]; then
+            echo "Error: AMI ID not found or empty. Exiting."
+            exit 1
+          fi
 
-    - name: Trigger instance refresh
-      run: |
-        asg_name=$(cat asg_name.txt)
-        aws autoscaling start-instance-refresh --auto-scaling-group-name $asg_name --strategy Rolling
+          echo "AMI ID: $ami_id"
 
+          aws ec2 create-launch-template-version \
+            --launch-template-id "$launch_template_id" \
+            --source-version 1 \
+            --launch-template-data "{\"ImageId\":\"$ami_id\"}"
 
-  
+      - name: Refresh autoscaling group
+        run: |
+          asg_name=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
+          echo "Autoscaling group name: $asg_name"
+          aws autoscaling start-instance-refresh --auto-scaling-group-name $asg_name
