changed build workflow

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -92,15 +92,20 @@ jobs:
     - name: Get AMI ID
       id: get_ami_id
       run: |
-        ami_id=$(aws ec2 describe-images --filters "Name=tag:Name,Values=csye6225_$(date -u +\%Y_\%m_\%d_\%H_\%M_\%S)" --query 'Images[0].ImageId' --output text)
+        tag_name="csye6225_$(date -u +\%Y_\%m_\%d_\%H_\%M)"
+
+        echo "The tag name: $tag_name"
+
+        ami_id=$(aws ec2 describe-images --filters "Name=tag:Name,Values=$tag_name" --query 'Images[0].ImageId' --output text)
+    
+        if [ -z "$ami_id" ] || [ "$ami_id" = "None" ]; then
+          echo "Error: No valid AMI ID found for tag '$tag_name'. Exiting."
+          exit 1
+        fi
+
+        echo "Found AMI_ID: $ami_id"
         echo "AMI_ID=$ami_id" > ami_id.txt
 
-    - name: Fetch latest Auto Scaling Group name
-      id: fetch_asg_name
-      run: |
-        asg_name=$(aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[0].AutoScalingGroupName' --output text)
-        echo "ASG_NAME=$asg_name" > asg_name.txt
-      
     - name: Update Launch Template with new AMI ID
       run: |
         launch_template_id=$(aws ec2 describe-launch-templates --launch-template-name csye6225-dev-launch-template --region ${{ secrets.AMI_AWS_REGION }} --query 'LaunchTemplates[0].LaunchTemplateId' --output json)
@@ -128,14 +133,16 @@ jobs:
 
         aws ec2 create-launch-template-version \
           --launch-template-id $launch_template_id \
-          --source-version $ami_id \
+          --source-version 1 \
           --launch-template-data "$modified_launch_template_data"
 
 
     - name: Update Auto Scaling Group with new Launch Template
       run: |
-        asg_name=$(cat asg_name.txt)
-        launch_template_id=$(cat launch_template_id.txt)
+        asg_name=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
+
+        launch_template_id=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?AutoScalingGroupName=='$asg_name'].LaunchTemplate.LaunchTemplateId" --output text)
+
         aws autoscaling update-auto-scaling-group --auto-scaling-group-name $asg_name --launch-template LaunchTemplateId=$launch_template_id,Version=$launch_template_version
 
     - name: Trigger instance refresh
